#ifndef __HYPERION_CONFIG_HH__
#define __HYPERION_CONFIG_HH__

// OPTgen/Hawkeye-related defines.
#define OPTGEN_VECTOR_SIZE 0x80
#define OPTGEN_TIMER_SIZE 0x400

#define HYPERION_SAMPLER_TAG_BITS 16
#define HYPERION_SAMPLER_TAG_MASK ((1ULL << HYPERION_SAMPLER_TAG_BITS) - 1ULL)

#define HYPERION_PC_HISTORY_LENGTH 16

// Perceptron predictor parameters.
#define HYPERION_PERCEPTRON_WEIGHTS_BITS 0x6
#define HYPERION_PERCEPTRON_WEIGHTS_MIN - ((1 << (HYPERION_PERCEPTRON_WEIGHTS_BITS - 1)) - 1)
#define HYPERION_PERCEPTRON_WEIGHTS_MAX - (HYPERION_PERCEPTRON_WEIGHTS_MIN + 1)

#define HYPERION_PERCEPTRON_OUTPUT_BITS 0x9
#define HYPERION_PERCEPTRON_OUTPUT_MIN - ((1 << (HYPERION_PERCEPTRON_OUTPUT_BITS - 1)) - 1)
#define HYPERION_PERCEPTRON_OUTPUT_MAX - (HYPERION_PERCEPTRON_OUTPUT_MIN + 1)

// Probability-related Re-Reference Prediction Values.
#define HYPERION_RRPV_BITS 0x3
#define HYPERION_RRPV_MIN 0x0
#define HYPERION_RRPV_MAX (1ULL << HYPERION_RRPV_BITS) - 1ULL

// Set-Dueling related materials.
#define HYPERION_LEADER_SETS_TIER1 0x22
#define HYPERION_LEADER_SETS_TIER2 2 * HYPERION_LEADER_SETS_TIER1

#define HYPERION_PSEL_BITS 11
#define HYPERION_PSEL_MIN - ((1 << (HYPERION_PSEL_BITS - 1)) - 1)
#define HYPERION_PSEL_MAX - (HYPERION_PSEL_MIN + 1)

#endif // __HYPERION_CONFIG_HH__
